version: '3.1'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'Yello_Bank'
      MYSQL_ROOT_PASSWORD: "123456"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
      